steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Generate Firebase config from environment variables
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'generate-config']
    env:
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'FIREBASE_AUTHDOMAIN=${_FIREBASE_AUTHDOMAIN}'
      - 'FIREBASE_PROJECTID=${_FIREBASE_PROJECTID}'
      - 'FIREBASE_STORAGEBUCKET=${_FIREBASE_STORAGEBUCKET}'
      - 'FIREBASE_MESSAGINGSENDERID=${_FIREBASE_MESSAGINGSENDERID}'
      - 'FIREBASE_APPID=${_FIREBASE_APPID}'
      - 'FIREBASE_MEASUREMENTID=${_FIREBASE_MEASUREMENTID}'

  # Deploy to Firebase Hosting
  - name: 'gcr.io/firebase/deploy'
    args:
      - deploy
      - --project=${PROJECT_ID}
      - --only=hosting

substitutions:
  _FIREBASE_API_KEY: '__REPLACE_WITH_FIREBASE_API_KEY__'
  _FIREBASE_AUTHDOMAIN: '__REPLACE_WITH_FIREBASE_AUTHDOMAIN__'
  _FIREBASE_PROJECTID: '__REPLACE_WITH_FIREBASE_PROJECTID__'
  _FIREBASE_STORAGEBUCKET: '__REPLACE_WITH_FIREBASE_STORAGEBUCKET__'
  _FIREBASE_MESSAGINGSENDERID: '__REPLACE_WITH_FIREBASE_MESSAGINGSENDERID__'
  _FIREBASE_APPID: '__REPLACE_WITH_FIREBASE_APPID__'
  _FIREBASE_MEASUREMENTID: '__REPLACE_WITH_FIREBASE_MEASUREMENTID__'

options:
  machineType: 'N1_HIGHCPU_8'
